### ISSUE TITLE
/join not working, tutorial will be much helpful

### ISSUE THREAD

**Issue by Nesamani1** [Korgron/SquadBattle#1]

**Comment by MajorKorgi** [comment]
What exactly are you typing in the command line, and does the console display any error messages?

For the /join command, you have to specify which team you want to join. The name you need to give is specified in the config/team.json file.

For example: 
_config/team.json_
```
{
    "red": {       //<--- team name used for the command.
        
        "used":true,
        "spawnpoint": [1087.79, -2183.18, 30.93],
        "active": 0,
        "ped_model": "s_m_y_dockwork_01",
        "blip": {
            "sprite": 176,
            "color": 1,
            "scale": 1.5,
            "name": "Worker"
        }
    }
}
```

_command line_
```
/join red
```

**Comment by Nesamani1** [comment]
Yes, but the count on right top dosen't update after joining, and also even after assigning Admin, it still pops up You are not an admin

**Comment by MajorKorgi** [comment]
Okay, are you typing the command in the F8 console of the client as "join..." or in the built-in chat of the server as "/join..."?

Because in the F8 console, everything you type will be recognized as a command, so you don't need the "/" at the beginning of the command.


Please also check if there are any errors occurring at the start of the server/script, while joining the server, or during the use of commands and hand over the occurring error messages.

If there are no errors occurring and you already type the command in the F8 console without "/", please hand over the config/teams.json file as well as the config/settings.json file.
